version: "3"
services:
  pihole:
    image: diginc/pi-hole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      ServerIP: 192.168.1.100
      INTERFACE: enp0s25
      WEBPASSWORD: doctorpizza
    volumes:
      - '/home/jorge/pihole/pihole:/etc/pihole'
      - '/home/jorge/pihole/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --schedule "0 0 3 * * *"
    restart: unless-stopped
