version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      ServerIP: 192.168.1.201
      INTERFACE: eth0
      WEBPASSWORD: doctorpizza
      DNS1: 192.168.1.200
    volumes:
      - '/home/jorge/pihole/pihole:/etc/pihole'
      - '/home/jorge/pihole/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    dns:
      - 127.0.0.1
